### ISSUE TITLE
Add support for FRESH schemas

### ISSUE THREAD

**Issue by asm0dey** [thibaudcolas/jsonresume-theme-eloquent#17]
Please, add support for FRESH schemas:
https://github.com/fresh-standard/fresh-resume-schema

It's much more developed then JSONResume and has fields like "speaking", "writing" and so on, which can be extremely helpful for public personas

**Comment by thibaudcolas** [comment]
Hey @asm0dey, thanks for the suggestion. I like this idea in principle but I don’t think I’d work on this any time soon – it’s quite an undertaking, so I’d be unlikely to do this unless I worked on my own resume as well, which won’t happen for the time being. If/when I do though, I really like this idea, although I think I’d probably make it into a separate project rather than aim for compatibility of a single theme between the two formats.

In the meantime, if you or anyone else wants to take this on please go ahead. And we could add a link at the top of this project’s README pointing at the FRESH version of the theme.

**Comment by asm0dey** [comment]
How do you think what is the best way to create project for FRESH? What parts should be preserved and/or reused?

**Comment by thibaudcolas** [comment]
I’m not too familiar with it so not sure I’m the best placed to give guidance, but I guess I’d start by looking at the official themes (https://github.com/fresh-standard?utf8=%E2%9C%93&q=fresh-theme-&type=&language=), and the workflow they suggest to work on the themes. Then copy `jsonresume-theme-eloquent`’s main template into the FRESH theme workflow and start updating all of the sections to their FRESH equivalent.

**Comment by hkdobrev** [comment]
The Fresh standard seems to no longer be supported and the website is offline.

**Comment by thibaudcolas** [comment]
Thank you @hkdobrev! I’ll close this now.
