### ISSUE TITLE
Incompatible with NPM 3

### ISSUE THREAD

**Issue by benthemonkey** [thibaudcolas/jsonresume-theme-eloquent#3]
`partials.js` makes assumptions about the folder structure that are not valid for NPM 3 (a flat structure with all dependencies in the main `node_modules` directory). I don't have any suggestions for how to make it compatible with both versions of NPM, so feel free to mark this as Wont Fix.

**Comment by benthemonkey** [comment]
This is super hacky but I guess you could look at `process.env.NPM_VERSION`...

**Comment by thibaudcolas** [comment]
Ah, yes.

I can foresee all sorts of issues with that because while the structure is flatter by default, it might not be flat when there are conflicts between versions.

I'll think about it and come back to you!

**Comment by thibaudcolas** [comment]
I don't want to rely on too much magic so I can see three solutions:
- Finding a way to resolve a package's location, as `require()` does.
- Using `browserify` to create the browser bundle
- Including those files right inside the project's source instead of npm dependencies.

**Comment by thibaudcolas** [comment]
Ok... this should now be fixed. You can try the change with `npm install --save jsonresume-theme-eloquent@2.1.0`.

I wasn't very satisfied with the way the front-end assets were being handled anyway, so I went the extra mile to make this work as it should. Now those assets are compiled before the module is published to npm instead of at runtime. It makes the front-end toolchain more maintainable, and less hacky. It's also way faster and learner when you use the module as an end user (on install, on render).

I haven't tried it in npm 3 (not too keen on upgrading just yet), but since the dependencies are not even here anymore when you install the module, that will work. I've tried it on my own resume (https://github.com/ThibWeb/fullresume), and it seems to work fine. Let me know how it goes for you!

If you've stumbled into other annoyances while using this / can think of other ways to improve it please let me know :)
