### ISSUE TITLE
Theme not rendering on jsonresume.org

### ISSUE THREAD

**Issue by benthemonkey** [thibaudcolas/jsonresume-theme-eloquent#4]
Have a look at http://themes.jsonresume.org/eloquent (which you link to in your readme) and http://registry.jsonresume.org/#eloquent

**Comment by benthemonkey** [comment]
Here's what the page displays: https://gist.github.com/benthemonkey/6a3656553e044e86391c

**Comment by thibaudcolas** [comment]
Hey @benthemonkey, thanks for the report. 

Unfortunately I don't think I can do much about this, it seems to be a registry error. I've had issues with it before so I think it might be time for me to stop relying on this for the demo. I changed my demo link to point to a file in the repo (https://rawgit.com/ThibWeb/jsonresume-theme-eloquent/master/test/resume.html), and created an issue on the `theme-manager` project: https://github.com/jsonresume/theme-manager/issues/27.

I think I might distance this project even further apart from jsonresume.org by having a separate online renderer to edit the resume content or a separate command line tool (like `jsonresume-theme-eloquent resume.json`) to render the theme. Future stuff to consider.

---

Some debug info for reference.

The registry is able to render the theme at any version. I can see that http://themes.jsonresume.org/eloquent@2.2.0 fails with what you reported above, http://themes.jsonresume.org/eloquent@2.1.0 fails with another error and http://themes.jsonresume.org/eloquent@1.2.0 works as expected. It doesn't help much though because nothing has changed with how I require Handlebars between those versions.
- On my local machine the latest version of the theme works as expected on Node 0.10 / 0.12 / 4 / 5. 
- I just released a new version to force the registry to rebuild the theme.

**Comment by thibaudcolas** [comment]
This seems to be solved in 2.2.3 but I have no idea why. There's now a new error that also seems to be registry-related, will look into it.

**Comment by thibaudcolas** [comment]
For reference this is now fixed on all registry endpoints (http://themes.jsonresume.org/eloquent). I have no idea why. My changes didn't really relate to the errors that were displayed.

`¯\_(ツ)_/¯`

**Comment by benthemonkey** [comment]
:+1:
